config/routes.rb
Rails.application.routes.draw do
  resources :schedules
  devise_for :users
  root "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/visits/:id/new", to: "schedules#new_visit"
  resources :places
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :visits
  geocoded_by :address
  after_validation :geocode
  mount_uploader :image, ImageUploader
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many :visits
  belongs_to :user
  # belong_to :place, :through => :visits
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :schedules
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :schedule
  belongs_to :place
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:image])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @places = Place.all
    respond_to do |format|
      format.html
      format.json { render json: @places }
    end
  end

  def show
    @place = Place.find_by(id: params[:id])
    respond_to do |f|
      f.html
      f.json { render json: @place }
    end
  end

  def new
    @place = Place.new
  end

  def edit
  end

  def create
    place = Place.create(place_params)
    redirect_to places_path
  end

  # def update
  #   author = Author.find(params[:id])
  #   author.update(author_params)
  #   redirect_to author_path(author)
  # end

  # def destroy
  #   author = Author.find_by(id: params[:id])
  #   author.destroy
  #   redirect_to authors_path
  # end

  private

  def place_params
    params.require(:place).permit(:name, :address, :duration, :description, :latitude, :longitude, :image)
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index
    schedules = current_user.schedules
    schedules = schedules.map do |s|
      s.as_json(include: [:visits, :user])
    end
    render json: schedules
  end

  def show
    @schedule = Schedule.find_by id: params[:id]
    @day_visits = @schedule.visits.group_by do |visit|
      visit.day
    end
    respond_to do |f|
      f.html
      f.json { render json: {schedule: @schedule, visits: @schedule.visits.as_json(include: [:place])} }
    end
  end

  def new
    @schedule = Schedule.new
  end

  def create
    schedule = current_user.schedules.create(schedule_params)
    current_day = schedule.start_day
    count = 1
    while current_day <= schedule.end_day
      morning_start_time = current_day.midnight + 9.hours
      evening_end_time = current_day.midnight + 18.hours
      if current_day == schedule.start_day
        morning_start_time = schedule.start_day
      end
      if current_day == schedule.end_day
        evening_end_time = schedule.end_day
      end
      while morning_start_time < evening_end_time
        p = Place.all.sample
        current_search = 1
        while morning_start_time + p.duration.hours > evening_end_time && current_search <= 3
          p = Place.all.sample
          current_search += 1
        end
        if current_search <= 3
          schedule.visits.create day: count, place_id: p.id, start_time: morning_start_time, end_time: morning_start_time + p.duration.hours
        end
        morning_start_time += p.duration.hours
      end
      current_day += 1.day
      count += 1
    end

    redirect_to schedule
  end

  def new_visit
    visit = Visit.find params[:id]
    duration = visit.place.duration
    new_place = Place.order("RANDOM()").find_by("duration <= #{duration}")
    visit.place_id = new_place.id
    visit.save
    render json: visit.as_json(include: [:place])
  end

  private

  def schedule_params
    params.require(:schedule).permit(:city, :location, :image, :description, :start_day, :end_day)
  end
end

app/controllers/sightseenings_controller.rb
class SightseeningsController < ApplicationController
  def index
    @places = Sightseeing.all
  end

  def show
    @place = Sightseeing.find_by(id: params[:id])
  end

  def new
    @place = Sightseeing.new
  end

  def edit
  end

  def create
    place = Sightseeing.create(place_params)
    redirect_to sightseenings_path
  end

  # def update
  #   author = Author.find(params[:id])
  #   author.update(author_params)
  #   redirect_to author_path(author)
  # end

  # def destroy
  #   author = Author.find_by(id: params[:id])
  #   author.destroy
  #   redirect_to authors_path
  # end

  private

  def place_params
    params.require(:place).permit(:name, :location, :duration, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel Itinerary</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  
  <body>
  <nav class= "nav_style"> 
  <%= link_to 'Home', root_path, class: "nav_home" %>
    <% if user_signed_in? %>
    <%#-# when user login in it will show the nav bar for add new place and schedule an itinerary in Application.erb  -%>

    <%= link_to 'All Places', places_path, class: "nav_place" %>
    <%#= link_to 'Add new Place', new_place_path %>


    <%# ADD ALL SCHEDULE TO A SPICIFIC USER %>
    <%#= link_to 'Your Itinerary', schedule_path %>
    <span><%#= current_user.email %></span>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "registration"%>
    <% else%>
    <%= link_to "Log in", new_user_session_path, class: "registration" %>
  <%= link_to "Sign Up", new_user_registration_path, class: "registration" %>

<% end%>
  </nav>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
<div class="header">
<%# image_tag("hills.jpg", :alt => "edge",:class => "bottom") %>
<%# image_tag("lights.jpg", :alt => "edge",:class => "bottom") %> 
<%# image_tag("download.jpg", :alt => "edge") %>
<%# image_tag("images.jpg", :alt => "edge")  %> 
<%# image_tag("images1.jpg", :alt => "edge")  %> 
<div id="container">
    <img src="/images/lights.jpg">
    <img src="/images/download.jpeg">
</div>
<div id="container">
<img src="/images/images.jpeg">
<img src="/images/images1.jpeg">
</div>
<div id="container">
<img src="/images/hotel.jpg">
<img src="/images/hills.jpg">
</div>
<div id="container">
<img src="/images/download.jpeg">
<img src="/images/lights.jpg">
</div>
</div>
</div>





<% if current_user %>
<%= react_component "Router", { currentUser: current_user, schedules: current_user.schedules } %> <br>
<% else %>
<div class="home_img">

<%#= image_tag("hills.jpg", :alt => "edge") %>
 <%#= image_tag("lights.jpg", :alt => "edge") %>
 <%#= image_tag("download.jpg", :alt => "edge") %>
 <%#= image_tag("images.jpg", :alt => "edge") %> 
 <%#= image_tag("images1.jpg", :alt => "edge") %> 
</div>
<%#= react_component "Router" %>

<% end %>

app/views/places/_form.html.erb
<%= form_for @place do |f| %>
  <div class="form">
  <div>
    <%= f.label :name, "What is the name of the place:" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :description, "Describe the place:" %> 
    <%= f.text_area :description %>
    <br>
  </div>

  <div>
    <%= f.label :location, "Address:" %>
      <%= f.text_field :address %>
      <br>

    <%= f.label :latitude, "latitude." %>
    <%= f.number_field :latitude, step: 0.0000000001 %>
    <br>
    <%= f.label :longitude, "longitude." %>
    <%= f.number_field :longitude, step: 0.000000000001 %>
    <br>
 
  </div>
  <div>
  <%= f.label "Image" %>
  <%= f.file_field :image %>
</div>
<div>
    <%= f.label :duration, "Styaing hours:" %>
    <%= f.text_area :duration %> 
</div>
</div>

 <div class="f_form" >
  <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Places#edit</h1>
<p>Find me in app/views/places/edit.html.erb</p>

app/views/places/index.html.erb
<h2>List of your Places</h2>

<% @places.each do |p| %>
<li>
<%= link_to(p.name, place_path(p)) %>

<br><br>
</li>
<% end %>
</ul>

app/views/places/new.html.erb
<h2 class="form_title2"> Add a new place</h2>


<%= render partial: 'form' %>

app/views/places/show.html.erb
<p class="title">About the place: <br> </p>
<p class="content"><%= @place.description %></p>
<p class="title"> Staying hours: <br>
<p class="content"><%= @place.duration %><br></p>
<%# <p>location: <%#= @place.address %>
<p class="title"> Pictures of the place : <br> </p>
<img class="place_img", src="<%= @place.image %>"> 

<div id="map" style="height:250px;width:600px;margin:0 auto; border: 1px solid black;"></div>
   <script>
      function initMap() {

    var myLatLng = {lat: <%= @place.latitude %>, lng: <%= @place.longitude %>};
    console.log(myLatLng);
    var map = new google.maps.Map(document.getElementById('map'), {
      center: myLatLng,
      zoom: 9});

      var marker = new google.maps.Marker({
      map: map,
      position: myLatLng,
      title: "<%= @place.name %>"
      
    });
  }
   </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCeVTVg2d7rXRz5HYLUYlaoDwsOyBgNJR4lback=initMap" async defer>
                    </script>

app/views/schedules/_form.html.erb
<div class="form">
<%= form_for @schedule do |f| %>
  <div>
    <%= f.label :city, "City :" %>
    <%= f.text_field :city  %>
  </div>

  <div>
    <%= f.label :start_day, "Arravial date :" %>
    <%= f.datetime_field :start_day %>
  </div>

<div >
    <%= f.label :end_day, "Departure date :" %>
    <%= f.datetime_field :end_day %>
  </div>

 <div class="f_form" >
  <%= f.submit %>
  </div>
<% end %>
</div>

app/views/schedules/new.html.erb
<h4 class="title_form">  Plan your trip </h4>

<%= render partial: 'form' %>

app/views/schedules/show.html.erb
<h1><%= @schedule.city %></h1>

<% @day_visits.each do |key, value| %>
    <h2>Day <%= key %></h2>
    <ul>
    <% value.each do |visit| %>
        <li><%= visit.place.name %>: </li>
    <% end %>
    </ul>
<% end %>

app/views/sightseenings/_form.html.erb
<%= form_for @place do |f| %>
  <div>
    <%= f.label :name, "What is the name of the place?" %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :desciption, "Describe the place" %> <br>
    <%= f.text_area :desciption %>
  </div>
  <div>
    <%= f.label :image, "Add image?" %>
    <%= f.url_field :image %>
  </div>

<div>
    <%= f.label :duration, "Styaing hours ?" %>
    <%= f.text_area :duration %> 
</div>


  <%= f.submit %>
<% end %>